//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailSync.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerListMapping
    {
        public int Id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> ListId { get; set; }
        public bool IsUnsubscribed { get; set; }
        public bool IsActive { get; set; }
    
        public virtual CustomerList CustomerList { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
