//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailSync.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaign
    {
        public Campaign()
        {
            this.CampaignListMappings = new HashSet<CampaignListMapping>();
            this.Emails = new HashSet<Email>();
            this.EmailStatistics = new HashSet<EmailStatistic>();
            this.Reports = new HashSet<Report>();
            this.EmailDetails = new HashSet<EmailDetail>();
            this.ScheduleDetails = new HashSet<ScheduleDetail>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
    
        public virtual ICollection<CampaignListMapping> CampaignListMappings { get; set; }
        public virtual CampaignType CampaignType { get; set; }
        public virtual ICollection<Email> Emails { get; set; }
        public virtual ICollection<EmailStatistic> EmailStatistics { get; set; }
        public virtual ICollection<Report> Reports { get; set; }
        public virtual ICollection<EmailDetail> EmailDetails { get; set; }
        public virtual ICollection<ScheduleDetail> ScheduleDetails { get; set; }
    }
}
