//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailSync.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.CustomerListMappings = new HashSet<CustomerListMapping>();
            this.EmailStatistics = new HashSet<EmailStatistic>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsUnsubscribed { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<CustomerListMapping> CustomerListMappings { get; set; }
        public virtual ICollection<EmailStatistic> EmailStatistics { get; set; }
    }
}
