//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailSync.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerList
    {
        public CustomerList()
        {
            this.CampaignListMappings = new HashSet<CampaignListMapping>();
            this.CustomerListMappings = new HashSet<CustomerListMapping>();
            this.Emails = new HashSet<Email>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<CampaignListMapping> CampaignListMappings { get; set; }
        public virtual ICollection<CustomerListMapping> CustomerListMappings { get; set; }
        public virtual ICollection<Email> Emails { get; set; }
    }
}
