//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailSync.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailDetail
    {
        public int Id { get; set; }
        public int CampaignsId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsActive { get; set; }
        public string emailSubject { get; set; }
        public string fromName { get; set; }
        public string fromemail { get; set; }
    
        public virtual Campaign Campaign { get; set; }
    }
}
