//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailSync.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailStatistic
    {
        public int Id { get; set; }
        public Nullable<int> ReportId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> CampaignId { get; set; }
        public bool IsOpen { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> OpenedDate { get; set; }
        public Nullable<int> EmailId { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
    
        public virtual Campaign Campaign { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Report Report { get; set; }
        public virtual Email Email { get; set; }
    }
}
