//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailSync.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public Report()
        {
            this.EmailStatistics = new HashSet<EmailStatistic>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CampaignId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Campaign Campaign { get; set; }
        public virtual ICollection<EmailStatistic> EmailStatistics { get; set; }
    }
}
