//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailSync.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleDetail
    {
        public int Id { get; set; }
        public bool IsOnce { get; set; }
        public bool IsEveryDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CampaignId { get; set; }
    
        public virtual Campaign Campaign { get; set; }
    }
}
